# Generated by Django 4.2.5 on 2023-09-21 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='device_model',
            new_name='Device',
        ),
        migrations.RenameModel(
            old_name='registername',
            new_name='Register',
        ),
    ]
