# Generated by Django 4.2 on 2023-09-21 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_server', '0004_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackAndTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_and_trace_id', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('speed', models.FloatField(max_length=10)),
                ('direction', models.CharField(max_length=50)),
                ('longitude', models.DecimalField(decimal_places=10, default=0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=10, default=0, max_digits=10)),
                ('extra_info', models.JSONField()),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_server.device')),
            ],
        ),
    ]
