# Generated by Django 4.2 on 2023-09-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='device',
            table='device',
        ),
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
