# Generated by Django 4.2 on 2023-09-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackAndTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('speed', models.FloatField(max_length=10)),
                ('direction', models.CharField(max_length=50)),
                ('longitude', models.FloatField(max_length=10)),
                ('latitude', models.FloatField(max_length=10)),
                ('extra_info', models.JSONField()),
            ],
        ),
    ]
