# Generated by Django 4.2.5 on 2023-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_server', '0006_remove_trackandtrace_track_and_trace_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='service',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackandtrace',
            name='latitude',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trackandtrace',
            name='longitude',
            field=models.FloatField(max_length=10),
        ),
    ]
